//
// Updated on 11/12/25.
// Copyright © 2025. All rights reserved.///
/// @Generated by Mockolo
///

import FeatureToggleKit
import Foundation

// MARK: - FeatureToggleKitMock

public final class FeatureToggleKitMock: FeatureToggleKit, @unchecked Sendable {
  // MARK: Lifecycle

  public init() {}

  // MARK: Public

  public var getBoolValueCallCount: Int {
    getBoolValueState.withLock(\.callCount)
  }

  public var getBoolValueHandler: (@Sendable (String, Bool) -> Bool)? {
    get { getBoolValueState.withLock(\.handler) }
    set { getBoolValueState.withLock { $0.handler = newValue } }
  }

  public var getStringValueCallCount: Int {
    getStringValueState.withLock(\.callCount)
  }

  public var getStringValueHandler: (@Sendable (String, String) -> String)? {
    get { getStringValueState.withLock(\.handler) }
    set { getStringValueState.withLock { $0.handler = newValue } }
  }

  public var getLongValueCallCount: Int {
    getLongValueState.withLock(\.callCount)
  }

  public var getLongValueHandler: (@Sendable (String, Int64) -> Int64)? {
    get { getLongValueState.withLock(\.handler) }
    set { getLongValueState.withLock { $0.handler = newValue } }
  }

  public var getDoubleValueCallCount: Int {
    getDoubleValueState.withLock(\.callCount)
  }

  public var getDoubleValueHandler: (@Sendable (String, Double) -> Double)? {
    get { getDoubleValueState.withLock(\.handler) }
    set { getDoubleValueState.withLock { $0.handler = newValue } }
  }

  public var getJSONValueCallCount: Int {
    getJSONValueState.withLock(\.callCount)
  }

  public var getJSONValueHandler: (@Sendable (String, FeatureToggleDictionary) -> FeatureToggleDictionary)? {
    get { getJSONValueState.withLock(\.handler) }
    set { getJSONValueState.withLock { $0.handler = newValue } }
  }

  public var fetchAllFeatureTogglesCallCount: Int {
    fetchAllFeatureTogglesState.withLock(\.callCount)
  }

  public var fetchAllFeatureTogglesHandler: (@Sendable () -> FeatureToggleDictionary)? {
    get { fetchAllFeatureTogglesState.withLock(\.handler) }
    set { fetchAllFeatureTogglesState.withLock { $0.handler = newValue } }
  }

  public var resetAllFeatureTogglesCallCount: Int {
    resetAllFeatureTogglesState.withLock(\.callCount)
  }

  public var resetAllFeatureTogglesHandler: (@Sendable () -> Void)? {
    get { resetAllFeatureTogglesState.withLock(\.handler) }
    set { resetAllFeatureTogglesState.withLock { $0.handler = newValue } }
  }

  public var setupCallCount: Int {
    setupState.withLock(\.callCount)
  }

  public var setupHandler: (@Sendable ([FeatureToggleDefinitionProvider]) -> Void)? {
    get { setupState.withLock(\.handler) }
    set { setupState.withLock { $0.handler = newValue } }
  }

  public var addListenerCallCount: Int {
    addListenerState.withLock(\.callCount)
  }

  public var addListenerHandler: (@Sendable (FeatureToggleKitListener) -> Void)? {
    get { addListenerState.withLock(\.handler) }
    set { addListenerState.withLock { $0.handler = newValue } }
  }

  public var removeListenerCallCount: Int {
    removeListenerState.withLock(\.callCount)
  }

  public var removeListenerHandler: (@Sendable (FeatureToggleKitListener) -> Void)? {
    get { removeListenerState.withLock(\.handler) }
    set { removeListenerState.withLock { $0.handler = newValue } }
  }

  public var addListenersCallCount: Int {
    addListenersState.withLock(\.callCount)
  }

  public var addListenersHandler: (@Sendable ([FeatureToggleKitListener]) -> Void)? {
    get { addListenersState.withLock(\.handler) }
    set { addListenersState.withLock { $0.handler = newValue } }
  }

  public var removeAllListenersCallCount: Int {
    removeAllListenersState.withLock(\.callCount)
  }

  public var removeAllListenersHandler: (@Sendable () -> Void)? {
    get { removeAllListenersState.withLock(\.handler) }
    set { removeAllListenersState.withLock { $0.handler = newValue } }
  }

  public var updateLocalCallCount: Int {
    updateLocalState.withLock(\.callCount)
  }

  public var updateLocalHandler: (@Sendable (String, FeatureToggleValue) async -> Void)? {
    get { updateLocalState.withLock(\.handler) }
    set { updateLocalState.withLock { $0.handler = newValue } }
  }

  public var clearCacheCallCount: Int {
    clearCacheState.withLock(\.callCount)
  }

  public var clearCacheHandler: (@Sendable () -> Void)? {
    get { clearCacheState.withLock(\.handler) }
    set { clearCacheState.withLock { $0.handler = newValue } }
  }

  public var getFeatureToggleTweakCallCount: Int {
    getFeatureToggleTweakState.withLock(\.callCount)
  }

  public var getFeatureToggleTweakHandler: (@Sendable (FeatureToggleDefinition) -> FeatureToggleTweak?)? {
    get { getFeatureToggleTweakState.withLock(\.handler) }
    set { getFeatureToggleTweakState.withLock { $0.handler = newValue } }
  }

  public func getBoolValue(key: String, fallbackValue: Bool) -> Bool {
    let getBoolValueHandler = getBoolValueState.withLock { state in
      state.callCount += 1
      return state.handler
    }
    if let getBoolValueHandler {
      return getBoolValueHandler(key, fallbackValue)
    }
    return false
  }

  public func getStringValue(key: String, fallbackValue: String) -> String {
    let getStringValueHandler = getStringValueState.withLock { state in
      state.callCount += 1
      return state.handler
    }
    if let getStringValueHandler {
      return getStringValueHandler(key, fallbackValue)
    }
    return ""
  }

  public func getLongValue(key: String, fallbackValue: Int64) -> Int64 {
    let getLongValueHandler = getLongValueState.withLock { state in
      state.callCount += 1
      return state.handler
    }
    if let getLongValueHandler {
      return getLongValueHandler(key, fallbackValue)
    }
    return 0
  }

  public func getDoubleValue(key: String, fallbackValue: Double) -> Double {
    let getDoubleValueHandler = getDoubleValueState.withLock { state in
      state.callCount += 1
      return state.handler
    }
    if let getDoubleValueHandler {
      return getDoubleValueHandler(key, fallbackValue)
    }
    return 0.0
  }

  public func getJSONValue(key: String, fallbackValue: FeatureToggleDictionary) -> FeatureToggleDictionary {
    let getJSONValueHandler = getJSONValueState.withLock { state in
      state.callCount += 1
      return state.handler
    }
    if let getJSONValueHandler {
      return getJSONValueHandler(key, fallbackValue)
    }
    fatalError("getJSONValueHandler returns can't have a default value thus its handler must be set")
  }

  public func fetchAllFeatureToggles() -> FeatureToggleDictionary {
    let fetchAllFeatureTogglesHandler = fetchAllFeatureTogglesState.withLock { state in
      state.callCount += 1
      return state.handler
    }
    if let fetchAllFeatureTogglesHandler {
      return fetchAllFeatureTogglesHandler()
    }
    fatalError("fetchAllFeatureTogglesHandler returns can't have a default value thus its handler must be set")
  }

  public func resetAllFeatureToggles() {
    let resetAllFeatureTogglesHandler = resetAllFeatureTogglesState.withLock { state in
      state.callCount += 1
      return state.handler
    }
    if let resetAllFeatureTogglesHandler {
      resetAllFeatureTogglesHandler()
    }
  }

  public func setup(definitionProviders: [FeatureToggleDefinitionProvider]) {
    let setupHandler = setupState.withLock { state in
      state.callCount += 1
      return state.handler
    }
    if let setupHandler {
      setupHandler(definitionProviders)
    }
  }

  public func addListener(_ listener: FeatureToggleKitListener) {
    let addListenerHandler = addListenerState.withLock { state in
      state.callCount += 1
      return state.handler
    }
    if let addListenerHandler {
      addListenerHandler(listener)
    }
  }

  public func removeListener(_ listener: FeatureToggleKitListener) {
    let removeListenerHandler = removeListenerState.withLock { state in
      state.callCount += 1
      return state.handler
    }
    if let removeListenerHandler {
      removeListenerHandler(listener)
    }
  }

  public func addListeners(_ listeners: [FeatureToggleKitListener]) {
    let addListenersHandler = addListenersState.withLock { state in
      state.callCount += 1
      return state.handler
    }
    if let addListenersHandler {
      addListenersHandler(listeners)
    }
  }

  public func removeAllListeners() {
    let removeAllListenersHandler = removeAllListenersState.withLock { state in
      state.callCount += 1
      return state.handler
    }
    if let removeAllListenersHandler {
      removeAllListenersHandler()
    }
  }

  public func updateLocal(key: String, newValue: FeatureToggleValue) async {
    let updateLocalHandler = updateLocalState.withLock { state in
      state.callCount += 1
      return state.handler
    }
    if let updateLocalHandler {
      await updateLocalHandler(key, newValue)
    }
  }

  public func clearCache() {
    let clearCacheHandler = clearCacheState.withLock { state in
      state.callCount += 1
      return state.handler
    }
    if let clearCacheHandler {
      clearCacheHandler()
    }
  }

  public func getFeatureToggleTweak(_ definition: FeatureToggleDefinition) -> FeatureToggleTweak? {
    let getFeatureToggleTweakHandler = getFeatureToggleTweakState.withLock { state in
      state.callCount += 1
      return state.handler
    }
    if let getFeatureToggleTweakHandler {
      return getFeatureToggleTweakHandler(definition)
    }
    return nil
  }

  // MARK: Private

  private let getBoolValueState = MockoloMutex(MockoloHandlerState<Never, @Sendable (String, Bool) -> Bool>())

  private let getStringValueState = MockoloMutex(MockoloHandlerState<Never, @Sendable (String, String) -> String>())

  private let getLongValueState = MockoloMutex(MockoloHandlerState<Never, @Sendable (String, Int64) -> Int64>())

  private let getDoubleValueState = MockoloMutex(MockoloHandlerState<Never, @Sendable (String, Double) -> Double>())

  private let getJSONValueState = MockoloMutex(MockoloHandlerState<Never, @Sendable (String, FeatureToggleDictionary) -> FeatureToggleDictionary>())

  private let fetchAllFeatureTogglesState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> FeatureToggleDictionary>())

  private let resetAllFeatureTogglesState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())

  private let setupState = MockoloMutex(MockoloHandlerState<Never, @Sendable ([FeatureToggleDefinitionProvider]) -> Void>())

  private let addListenerState = MockoloMutex(MockoloHandlerState<Never, @Sendable (FeatureToggleKitListener) -> Void>())

  private let removeListenerState = MockoloMutex(MockoloHandlerState<Never, @Sendable (FeatureToggleKitListener) -> Void>())

  private let addListenersState = MockoloMutex(MockoloHandlerState<Never, @Sendable ([FeatureToggleKitListener]) -> Void>())

  private let removeAllListenersState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())

  private let updateLocalState = MockoloMutex(MockoloHandlerState<Never, @Sendable (String, FeatureToggleValue) async -> Void>())

  private let clearCacheState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> Void>())

  private let getFeatureToggleTweakState = MockoloMutex(MockoloHandlerState<Never, @Sendable (FeatureToggleDefinition) -> FeatureToggleTweak?>())
}

// MARK: - FeatureToggleValueProvidingMock

public class FeatureToggleValueProvidingMock: FeatureToggleValueProviding {
  // MARK: Lifecycle

  public init() {}

  // MARK: Public

  public private(set) var getBoolValueCallCount = 0
  public var getBoolValueHandler: ((String, Bool) -> Bool)?
  public private(set) var getStringValueCallCount = 0
  public var getStringValueHandler: ((String, String) -> String)?
  public private(set) var getLongValueCallCount = 0
  public var getLongValueHandler: ((String, Int64) -> Int64)?
  public private(set) var getDoubleValueCallCount = 0
  public var getDoubleValueHandler: ((String, Double) -> Double)?
  public private(set) var getJSONValueCallCount = 0
  public var getJSONValueHandler: ((String, FeatureToggleDictionary) -> FeatureToggleDictionary)?

  public func getBoolValue(key: String, fallbackValue: Bool) -> Bool {
    getBoolValueCallCount += 1
    if let getBoolValueHandler {
      return getBoolValueHandler(key, fallbackValue)
    }
    return false
  }

  public func getStringValue(key: String, fallbackValue: String) -> String {
    getStringValueCallCount += 1
    if let getStringValueHandler {
      return getStringValueHandler(key, fallbackValue)
    }
    return ""
  }

  public func getLongValue(key: String, fallbackValue: Int64) -> Int64 {
    getLongValueCallCount += 1
    if let getLongValueHandler {
      return getLongValueHandler(key, fallbackValue)
    }
    return 0
  }

  public func getDoubleValue(key: String, fallbackValue: Double) -> Double {
    getDoubleValueCallCount += 1
    if let getDoubleValueHandler {
      return getDoubleValueHandler(key, fallbackValue)
    }
    return 0.0
  }

  public func getJSONValue(key: String, fallbackValue: FeatureToggleDictionary) -> FeatureToggleDictionary {
    getJSONValueCallCount += 1
    if let getJSONValueHandler {
      return getJSONValueHandler(key, fallbackValue)
    }
    fatalError("getJSONValueHandler returns can't have a default value thus its handler must be set")
  }
}

// MARK: - FeatureToggleExperimentManagingMock

public class FeatureToggleExperimentManagingMock: FeatureToggleExperimentManaging {
  // MARK: Lifecycle

  public init() {}

  // MARK: Public

  public private(set) var fetchAllFeatureTogglesCallCount = 0
  public var fetchAllFeatureTogglesHandler: (() -> FeatureToggleDictionary)?
  public private(set) var resetAllFeatureTogglesCallCount = 0
  public var resetAllFeatureTogglesHandler: (() -> Void)?

  public func fetchAllFeatureToggles() -> FeatureToggleDictionary {
    fetchAllFeatureTogglesCallCount += 1
    if let fetchAllFeatureTogglesHandler {
      return fetchAllFeatureTogglesHandler()
    }
    fatalError("fetchAllFeatureTogglesHandler returns can't have a default value thus its handler must be set")
  }

  public func resetAllFeatureToggles() {
    resetAllFeatureTogglesCallCount += 1
    if let resetAllFeatureTogglesHandler {
      resetAllFeatureTogglesHandler()
    }
  }
}

// MARK: - FeatureToggleSetupManagingMock

public class FeatureToggleSetupManagingMock: FeatureToggleSetupManaging {
  // MARK: Lifecycle

  public init() {}

  // MARK: Public

  public private(set) var setupCallCount = 0
  public var setupHandler: (([FeatureToggleDefinitionProvider]) -> Void)?

  public func setup(definitionProviders: [FeatureToggleDefinitionProvider]) {
    setupCallCount += 1
    if let setupHandler {
      setupHandler(definitionProviders)
    }
  }
}

// MARK: - FeatureToggleListenerManagingMock

public class FeatureToggleListenerManagingMock: FeatureToggleListenerManaging {
  // MARK: Lifecycle

  public init() {}

  // MARK: Public

  public private(set) var addListenerCallCount = 0
  public var addListenerHandler: ((FeatureToggleKitListener) -> Void)?
  public private(set) var removeListenerCallCount = 0
  public var removeListenerHandler: ((FeatureToggleKitListener) -> Void)?
  public private(set) var addListenersCallCount = 0
  public var addListenersHandler: (([FeatureToggleKitListener]) -> Void)?
  public private(set) var removeAllListenersCallCount = 0
  public var removeAllListenersHandler: (() -> Void)?

  public func addListener(_ listener: FeatureToggleKitListener) {
    addListenerCallCount += 1
    if let addListenerHandler {
      addListenerHandler(listener)
    }
  }

  public func removeListener(_ listener: FeatureToggleKitListener) {
    removeListenerCallCount += 1
    if let removeListenerHandler {
      removeListenerHandler(listener)
    }
  }

  public func addListeners(_ listeners: [FeatureToggleKitListener]) {
    addListenersCallCount += 1
    if let addListenersHandler {
      addListenersHandler(listeners)
    }
  }

  public func removeAllListeners() {
    removeAllListenersCallCount += 1
    if let removeAllListenersHandler {
      removeAllListenersHandler()
    }
  }
}

// MARK: - FeatureToggleTweakCacheManagingMock

public class FeatureToggleTweakCacheManagingMock: FeatureToggleTweakCacheManaging {
  // MARK: Lifecycle

  public init() {}

  // MARK: Public

  public private(set) var updateLocalCallCount = 0
  public var updateLocalHandler: ((String, FeatureToggleValue) async -> Void)?
  public private(set) var clearCacheCallCount = 0
  public var clearCacheHandler: (() -> Void)?
  public private(set) var getFeatureToggleTweakCallCount = 0
  public var getFeatureToggleTweakHandler: ((FeatureToggleDefinition) -> FeatureToggleTweak?)?

  public func updateLocal(key: String, newValue: FeatureToggleValue) async {
    updateLocalCallCount += 1
    if let updateLocalHandler {
      await updateLocalHandler(key, newValue)
    }
  }

  public func clearCache() {
    clearCacheCallCount += 1
    if let clearCacheHandler {
      clearCacheHandler()
    }
  }

  public func getFeatureToggleTweak(_ definition: FeatureToggleDefinition) -> FeatureToggleTweak? {
    getFeatureToggleTweakCallCount += 1
    if let getFeatureToggleTweakHandler {
      return getFeatureToggleTweakHandler(definition)
    }
    return nil
  }
}

private func warnIfNotSendable<each T>(function: String = #function, _: repeat each T) {
  print("At \(function), the captured arguments are not Sendable, it is not concurrency-safe.")
}

private func warnIfNotSendable<each T: Sendable>(function: String = #function, _: repeat each T) {}

// MARK: - MockoloMutex

/// Will be replaced to `Synchronization.Mutex` in future.
private final class MockoloMutex<Value>: @unchecked Sendable {
  // MARK: Lifecycle

  init(_ initialValue: Value) {
    value = initialValue
  }

  // MARK: Internal

  #if compiler(>=6.0)
  borrowing func withLock<Result, E: Error>(_ body: (inout sending Value) throws(E) -> Result) throws(E) -> sending Result {
    lock.lock()
    defer { lock.unlock() }
    return try body(&value)
  }
  #else
  func withLock<Result>(_ body: (inout Value) throws -> Result) rethrows -> Result {
    lock.lock()
    defer { lock.unlock() }
    return try body(&value)
  }
  #endif

  // MARK: Private

  private let lock = NSLock()
  private var value: Value
}

// MARK: - MockoloUnsafeTransfer

private struct MockoloUnsafeTransfer<Value>: @unchecked Sendable {
  // MARK: Lifecycle

  init(_ value: Value) {
    self.value = value
  }

  // MARK: Internal

  var value: Value
}

// MARK: - MockoloHandlerState

private struct MockoloHandlerState<Arg, Handler> {
  var argValues: [MockoloUnsafeTransfer<Arg>] = []
  var handler: Handler?
  var callCount = 0
}
