//
// Updated on 11/12/25.
// Copyright © 2025. All rights reserved.///
/// @Generated by Mockolo
///

import FeatureToggleKit
import Foundation

// MARK: - FeatureToggleDefinitionProviderMock

public final class FeatureToggleDefinitionProviderMock: FeatureToggleDefinitionProvider, @unchecked Sendable {
  // MARK: Lifecycle

  public init() {}
  public init(name: String = "", definitions: [FeatureToggleDefinition] = [FeatureToggleDefinition]()) {
    self.name = name
    self.definitions = definitions
  }

  // MARK: Public

  public var name = ""

  public var definitions = [FeatureToggleDefinition]()
}

private func warnIfNotSendable<each T>(function: String = #function, _: repeat each T) {
  print("At \(function), the captured arguments are not Sendable, it is not concurrency-safe.")
}

private func warnIfNotSendable<each T: Sendable>(function: String = #function, _: repeat each T) {}

// MARK: - MockoloMutex

/// Will be replaced to `Synchronization.Mutex` in future.
private final class MockoloMutex<Value>: @unchecked Sendable {
  // MARK: Lifecycle

  init(_ initialValue: Value) {
    value = initialValue
  }

  // MARK: Internal

  #if compiler(>=6.0)
  borrowing func withLock<Result, E: Error>(_ body: (inout sending Value) throws(E) -> Result) throws(E) -> sending Result {
    lock.lock()
    defer { lock.unlock() }
    return try body(&value)
  }
  #else
  func withLock<Result>(_ body: (inout Value) throws -> Result) rethrows -> Result {
    lock.lock()
    defer { lock.unlock() }
    return try body(&value)
  }
  #endif

  // MARK: Private

  private let lock = NSLock()
  private var value: Value
}

// MARK: - MockoloUnsafeTransfer

private struct MockoloUnsafeTransfer<Value>: @unchecked Sendable {
  // MARK: Lifecycle

  init(_ value: Value) {
    self.value = value
  }

  // MARK: Internal

  var value: Value
}

// MARK: - MockoloHandlerState

private struct MockoloHandlerState<Arg, Handler> {
  var argValues: [MockoloUnsafeTransfer<Arg>] = []
  var handler: Handler?
  var callCount = 0
}
